# Example Site settings

#google_analytics: UA-NNNNNNNN-N

#Site Author
author:
  name: "Zack Lee"
  
tiitle: "Zack's Progress Report"

header_pages:
  - index.md
  - paper_review.md
  - theory.md
  - research.md
  - life.md
  - comments.md

footer: '<h2 class="contact">Contact Information</h2>'


style: hacker

listen_for_clients_preferred_style: true

plugins:
  - jekyll-seo-tag

url: "https://zackcglee.github.io"

  # Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: paper, theory, life
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

    
markdown: kramdown
# !github-pages! mandatory › https://help.github.com/articles/using-jekyll-with-pages/#configuration-settings-you-cannot-change
# Since Jekyll 3 the default highlighter is Rouge (replaced Pygments.rb in v44)
highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1