# Example Site settings

google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - paper_review.md
  - theory.md
  - life.md
  - comments.md

footer: '<h2>Contact</h2>  leechanggong@gmail.com'

style: hacker

listen_for_clients_preferred_style: true

plugins:
  - jekyll-seo-tag

url: "https://zackcglee.github.io"