# Example Site settings

google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - paper_review.md
  - theory.md
  - life.md
  - comm.md

footer: '<h2>Contact</h2>  leechanggong@gmail.com'

style: hacker

listen_for_clients_preferred_style: true

plugins:
  - jekyll-seo-tag

url: "https://zackcglee.github.io"

comments:
  provider               : "disqus" # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname            : "zackcglee" # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments

  # Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true